name: WakaTime Readme

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          API_BASE_URL: ${{ secrets.WAKAPI_BASE_URL }}
          WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: last_30_days
          SHOW_TIME: true
          REPOSITORY: pphatdev/pphatdev
          SHOW_TITLE: false
          SECTION_NAME: waka
          CODE_LANG: txt
          LANG_COUNT: 5
          SHOW_TOTAL: false
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: false
          TARGET_BRANCH: main  # Not set, update to your default branch
          TARGET_PATH: README.md  # Not set, update to your readme path
          COMMITTER_NAME: GitHub Action  # Not set, update if needed
          COMMITTER_EMAIL: action@github.com  # Not set, update if needed
          AUTHOR_NAME: GitHub Action  # Not set, update if needed
          AUTHOR_EMAIL: action@github.com  # Not set, update if needed
